#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Semantique  # The title of the book. Will be placed in the left navbar.
author                      : valentina borghesani # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : NeuroLang.png  # A path to the book logo
bibtex_bibfiles:
   - references.bib

# Parse and render settings
parse:
  myst_extended_syntax: true

# HTML-specific settings
#html:
  #favicon                   : "cneuromod_favicon.png"  # A path to a favicon image